language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

# services:
# 	-docker

install:
  - make deps

script:
  - make linux
